#! /bin/bash

### BEGIN INIT INFO
# Provides:          korel_scheduler
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/stop korel_scheduler
### END INIT INFO

#set -e

. /lib/lsb/init-functions

if [[ ! -d "$KOREL_RWS_DIR" ]]; then
    KOREL_RWS_DIR=/opt/korel_rws
fi

if [[ "$USER" == "root" ]]; then
    KOREL_RWS_USER="korel"
else
    KOREL_RWS_USER="$USER"
fi

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=${KOREL_RWS_DIR}/korel_rws
PIDFILE=${KOREL_RWS_DIR}/var/run/korel_rws.pid

SCHEDULER=${KOREL_RWS_DIR}/korel_scheduler
SCHEDULER_PIDFILE=${KOREL_RWS_DIR}/var/run/korel_scheduler.pid

# Arguments to atd
#
ARGS="-d"

#test -x $DAEMON || exit 0

case "$1" in
    start)
        log_action_begin_msg "Starting korel_rws daemon"
        #start-stop-daemon --start --quiet --pidfile "$PIDFILE" --chuid "$KOREL_RWS_USER" --exec "$DAEMON" -- $ARGS
        start-stop-daemon --start --quiet --pidfile "$PIDFILE" --chuid "$KOREL_RWS_USER" --exec "$SCHEDULER" -- $ARGS
        log_action_end_msg $?
        ;;
    stop)
        log_action_begin_msg "Stopping korel_rws daemon"
        #start-stop-daemon --stop --quiet --pidfile "$PIDFILE"
        start-stop-daemon --stop --quiet --pidfile "$SCHEDULER_PIDFILE"
        log_action_end_msg $?
        ;;
    restart|force-reload)
        "$0" stop
        sleep 2
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

exit 0
